storage:
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
datalab:
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
environmentconfig:
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  iam:
    realm: {{ getenv "REALM" "eoepca" }}
  ingress:
    class: {{ getenv "INGRESS_CLASS" }}
    domain: {{ getenv "INGRESS_HOST" }}
    secret: wildcard-tls
  storage:
    endpoint: {{ getenv "S3_ENDPOINT" }}
    forcePathStyle: true
    provider: Other
    region: {{ getenv "S3_REGION" }}
    secretNamespace: workspace
    type: s3
  network:
    serviceCIDR: "10.43.0.0/12"
  packages:
    - name: awscli
      files:
        - image:
            url: ghcr.io/versioneer-tech/educates-extension-packages/awscli:v2.29.0
    - name: rclone
      files:
        - image:
            url: ghcr.io/versioneer-tech/educates-extension-packages/rclone:v1.71.0
  auth:
    type: none
  defaults:
    quota:
      storage: 8Gi
      budget: x-large