apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: workspace-admin-kong-proxy
  namespace: workspace
spec:
  scheme: https
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: workspace-admin
  namespace: workspace
spec:
  http:
    - name: workspace-admin
      match:
        hosts:
          - workspace-admin.{{ getenv "INGRESS_HOST" }}
        paths:
          - /*
      backends:
        - serviceName: workspace-admin-kong-proxy
          servicePort: 443
      plugins: []
{{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workspace-admin
  namespace: workspace
spec:
  dnsNames:
    - workspace-admin.{{ getenv "INGRESS_HOST" }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ getenv "CLUSTER_ISSUER" }}
  secretName: workspace-admin-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: workspace-admin
  namespace: workspace
spec:
  hosts:
    - workspace-admin.{{ getenv "INGRESS_HOST" }}
  secret:
    name: workspace-admin-tls
    namespace: workspace
{{- end }}
